spring.application.name=PersonalFinanceAdvisor
spring.datasource.url=jdbc:mysql://localhost:3306/finance_db
spring.datasource.username=root
spring.datasource.password=root
#spring.datasource.url=jdbc:mysql://finance-advisor.clcoe40yk9l9.eu-north-1.rds.amazonaws.com:3306/FinanceAdvisor
#spring.datasource.username=admin
#spring.datasource.password=Abhishek#123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abhishekmohapatra768@gmail.com
spring.mail.password=nbdkkakducdpsrhr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.security.user.name=abhi
spring.security.user.password=12345